### ISSUE TITLE
Build fails on Linux after merging utf8 branch

### ISSUE THREAD

**Issue by magnumripper** [teeshop/rexgen#43]
This is Ubuntu 16.04 LTS:
```
[ 80%] Building CXX object librexgen/CMakeFiles/librexgen.dir/c/iterator.cpp.o
[ 83%] Building CXX object librexgen/CMakeFiles/librexgen.dir/c/simplestring.cpp.o
/home/magnum/src/rexgen/src/librexgen/c/simplestring.cpp: In function ‘int c_simplestring_to_utf8_string(c_simplestring_ptr, char*, size_t)’:
/home/magnum/src/rexgen/src/librexgen/c/simplestring.cpp:57:13: error: ‘runtime_error’ is not a member of ‘std’
       throw std::runtime_error("mblen(): conversion error");
             ^
/home/magnum/src/rexgen/src/librexgen/c/simplestring.cpp:63:13: error: ‘runtime_error’ is not a member of ‘std’
       throw std::runtime_error("wctomb(): conversion error");
             ^
librexgen/CMakeFiles/librexgen.dir/build.make:597: recipe for target 'librexgen/CMakeFiles/librexgen.dir/c/simplestring.cpp.o' failed
make[2]: *** [librexgen/CMakeFiles/librexgen.dir/c/simplestring.cpp.o] Error 1
CMakeFiles/Makefile2:123: recipe for target 'librexgen/CMakeFiles/librexgen.dir/all' failed
make[1]: *** [librexgen/CMakeFiles/librexgen.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```
Latest master commit without this problem is dc9ba1e4.

NOTE that under OSX the build completes just fine.

**Comment by teeshop** [comment]
Thank you for testing this. There was a missing include; I fixed this in master (2.0.3)
